services:
 - elasticsearch
language: node_js
node_js:
  - "8.10.0"
cache:
  directories:
    - "node_modules"
install:
  - yarn
before_script:
  - sleep 5
script:
  - yarn lint
  - nyc --reporter=lcov yarn test
  - codecov
