version: '3'
services:
  elasticsearch-hq:
    image: elastichq/elasticsearch-hq
    container_name: elasticsearch-hq
    ports:
      - "5000:5000"
    environment:
      HQ_DEFAULT_URL: http://172.29.10.21:9200
  redis-queue:
    image: "redis:alpine"
    container_name: redis-queue
    ports:
      - "6379:6379"
