---

- name: ensure default configuration is removed
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/conf.d/default.conf
  notify: nginx restart

- name: deliver nginx configuration
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ item.path }}/{{ item.file }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - file: "currenta.conf"
      path: "/etc/nginx/conf.d"
    - file: "nginx.conf"
      path: "/etc/nginx"
  notify: nginx restart

- name: ensure nginx started and enabled
  service:
    name: nginx
    state: started
    enabled: yes
